Add support for downloading mura and such

diff --git a/galileo-mura-setup b/galileo-mura-setup
--- a/galileo-mura-setup
+++ b/galileo-mura-setup
@@ -2,44 +2,72 @@
 
 set -euo pipefail
 
+cleanup_fail()
+{
+  rm -rf /tmp/mura || true
+}
+
 rm -rf /tmp/mura
 mkdir -p /tmp/mura
-
 /usr/bin/galileo-mura-extractor > /tmp/mura/info.txt
-
 display_serial=$(cat /tmp/mura/info.txt | sed -n 's/.*Display Serial: \(.*\)/\1/p')
-tar -xf /tmp/mura/blob.tar -C /tmp/mura
-rm -rf /tmp/mura/blob.tar
+deck_serial=$(cat /tmp/mura/info.txt | sed -n 's/.*Deck Serial: \(.*\)/\1/p')
+manufacturer=$(cat /tmp/mura/info.txt | sed -n 's/.*Manufacturer: \(.*\)/\1/p')
 
-# Make sure that we have the files.
-ls /tmp/mura/"$display_serial"_red.png > /dev/null
-ls /tmp/mura/"$display_serial"_green.png > /dev/null
-ls /tmp/mura/"$display_serial".json > /dev/null
+mura_base_path=/home/deck/.config/gamescope/mura
+mkdir -p "$mura_base_path"
 
-if ! grep -q "Manufacturer: SDC" /tmp/mura/info.txt; then
-  echo "Not using mura correction for this unit as it is not SDC." >&2
+if ./galileo-mura-download "$display_serial" "$deck_serial" "$mura_base_path"; then
+  rm -rf /tmp/mura
+  mkdir -p "$mura_base_path"/"$display_serial"
+  tar -xf "$mura_base_path"/"$display_serial".tar -C "$mura_base_path"/"$display_serial"
+  mura_path="$mura_base_path/$display_serial"
+else
+  tar -xf /tmp/mura/blob.tar -C /tmp/mura
+  rm -rf /tmp/mura/blob.tar
+  mura_path="/tmp/mura"
+fi
+
+if [ ! -f "$mura_path/$display_serial"_red.png ]; then
+  echo "Missing mura images, bailing out."
+  cleanup_fail
   exit 1
 fi
 
-json_major_version=$(sed -n 's/.*"version" : "\([0-9]\)\..*"/\1/p' /tmp/mura/"$display_serial".json)
+# Make sure that we have all the files.
+# This script is pipefail so if these commands fail we will exit out.
+ls "$mura_path/$display_serial"_red.png > /dev/null
+ls "$mura_path/$display_serial"_green.png > /dev/null
+ls "$mura_path/$display_serial".json > /dev/null
+
+if [ "$manufacturer" != "SDC" ]; then
+  echo "Not using mura correction for this unit as it is not SDC." >&2
+  cleanup_fail
+  exit 1
+fi
+
+json_major_version=$(sed -n 's/.*"version" : "\([0-9]\)\..*"/\1/p' "$mura_path/$display_serial".json)
 json_major_version="${json_major_version//[^[:digit:]]/}"
 
 use_mura=0
-if [ "$json_major_version" -eq 0 ]; then
-  use_mura=1
-elif [ "$json_major_version" -ge 2 ]; then
+if [ "$json_major_version" -ge 2 ]; then
   use_mura=1
 fi
 
 if [ "$use_mura" -eq 0 ]; then
   echo "Not using mura correction for this unit due to the mura version: \"$json_major_version\"" >&2
+  cleanup_fail
   exit 1
 fi
 
-json_serial=$(sed -n 's/.*"serialNumber"\s*:\s*"\([^"]*\)".*/\1/p' /tmp/mura/"$display_serial".json)
+json_serial=$(sed -n 's/.*"serialNumber"\s*:\s*"\([^"]*\)".*/\1/p' "$mura_path/$display_serial".json)
 if [[ "$display_serial" != "$json_serial" ]]; then
   echo "JSON serial didn't match display serial" >&2
+  cleanup_fail
   exit 1
 fi
 
-echo /tmp/mura/$display_serial
+echo "Success! All good. Using mura at: $mura_path"
+
+exit 0
+
